version: "3"

networks:
  project:

services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - project

  hub:
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - project
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://hub:4444/wd/hub/status"] 
      interval: 10s
      timeout: 5s
      retries: 3

  selenium-tests:
    build:
      context: ./SeleniumTests
      dockerfile: Dockerfile
    volumes:
      - ./SeleniumTests/TestResults:/SeleniumTests/TestResults
    networks:
      - project
    depends_on:
      - app
      - hub
      - chrome
      - proxy
      - web
      - frontend
  web:
    image: nginx:1.25-alpine3.17
    volumes:
      - ./backend:/www:rw
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - app
    networks:
      - project

  app:
    image: rcsnjszg/backend2023
    build:
      context: ./backend/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/www:rw
      - ./.env:/www/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - project

  db:
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ="${TZ}"
    volumes:
      - "./backend/docker/mysql/var/lib/mysql:/var/lib/mysql:rw"
      - "./backend/create_test_database.sh:/docker-entrypoint-initdb.d/create_test_database.sh"
      - "./backend/.env.testing:/docker-entrypoint-initdb.d/.env.testing:ro"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    networks:
      - project

  phpmyadmin:
    image: phpmyadmin:5.1-apache
    depends_on:
      - db
    environment:
        - PMA_ABSOLUTE_URI=http://localhost/phpmyadmin
    networks:
      - project

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    depends_on:
      app:
        condition: service_healthy
    networks:
      - project
     
  proxy:
    image: nginx:alpine
    ports:
     - 80:80
    volumes:
     - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - frontend
      - db
      - phpmyadmin
      - web
    networks:
     - project